# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beauty.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(552, 359)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.choosePathLabel = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.choosePathLabel.setReadOnly(True)
        self.choosePathLabel.setObjectName(_fromUtf8("choosePathLabel"))
        self.horizontalLayout.addWidget(self.choosePathLabel)
        self.choosePathButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choosePathButton.sizePolicy().hasHeightForWidth())
        self.choosePathButton.setSizePolicy(sizePolicy)
        self.choosePathButton.setObjectName(_fromUtf8("choosePathButton"))
        self.horizontalLayout.addWidget(self.choosePathButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 301, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.allPageNumLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.allPageNumLabel.setObjectName(_fromUtf8("allPageNumLabel"))
        self.horizontalLayout_2.addWidget(self.allPageNumLabel)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label, QtCore.Qt.AlignLeft)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 90, 269, 43))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.firstPageTextedit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.firstPageTextedit.setMinimumSize(QtCore.QSize(42, 0))
        self.firstPageTextedit.setText(_fromUtf8(""))
        self.firstPageTextedit.setEchoMode(QtGui.QLineEdit.Normal)
        self.firstPageTextedit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstPageTextedit.setPlaceholderText(_fromUtf8("1"))
        self.firstPageTextedit.setObjectName(_fromUtf8("firstPageTextedit"))
        self.horizontalLayout_3.addWidget(self.firstPageTextedit)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.finalPageTextedit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.finalPageTextedit.setText(_fromUtf8(""))
        self.finalPageTextedit.setFrame(True)
        self.finalPageTextedit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finalPageTextedit.setPlaceholderText(_fromUtf8("2"))
        self.finalPageTextedit.setObjectName(_fromUtf8("finalPageTextedit"))
        self.horizontalLayout_3.addWidget(self.finalPageTextedit)
        self.sendPageButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.sendPageButton.setObjectName(_fromUtf8("sendPageButton"))
        self.horizontalLayout_3.addWidget(self.sendPageButton)
        self.stopSend = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.stopSend.setEnabled(False)
        self.stopSend.setObjectName(_fromUtf8("stopSend"))
        self.horizontalLayout_3.addWidget(self.stopSend)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(320, 90, 201, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tellTitleNumLabel = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.tellTitleNumLabel.setEnabled(True)
        self.tellTitleNumLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.tellTitleNumLabel.setObjectName(_fromUtf8("tellTitleNumLabel"))
        self.horizontalLayout_4.addWidget(self.tellTitleNumLabel)
        self.titleNumLabel = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.titleNumLabel.setText(_fromUtf8(""))
        self.titleNumLabel.setObjectName(_fromUtf8("titleNumLabel"))
        self.horizontalLayout_4.addWidget(self.titleNumLabel)
        self.downloadButton = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.horizontalLayout_4.addWidget(self.downloadButton)
        self.downloadBar = QtGui.QProgressBar(self.centralwidget)
        self.downloadBar.setGeometry(QtCore.QRect(20, 160, 401, 31))
        self.downloadBar.setProperty("value", 0)
        self.downloadBar.setTextVisible(True)
        self.downloadBar.setInvertedAppearance(False)
        self.downloadBar.setObjectName(_fromUtf8("downloadBar"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(190, 220, 341, 71))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.randomBeauty = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.randomBeauty.setObjectName(_fromUtf8("randomBeauty"))
        self.horizontalLayout_5.addWidget(self.randomBeauty)
        self.openFolder = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.openFolder.setObjectName(_fromUtf8("openFolder"))
        self.horizontalLayout_5.addWidget(self.openFolder)
        self.QuitButton = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.horizontalLayout_5.addWidget(self.QuitButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 552, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.goToBeauty = QtGui.QMenu(self.menuBar)
        self.goToBeauty.setObjectName(_fromUtf8("goToBeauty"))
        self.aboutMenu = QtGui.QMenu(self.menuBar)
        self.aboutMenu.setObjectName(_fromUtf8("aboutMenu"))
        MainWindow.setMenuBar(self.menuBar)
        self.helpMenu = QtGui.QAction(MainWindow)
        self.helpMenu.setCheckable(False)
        self.helpMenu.setEnabled(True)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        self.aboutApp = QtGui.QAction(MainWindow)
        self.aboutApp.setObjectName(_fromUtf8("aboutApp"))
        self.aboutMenu.addAction(self.helpMenu)
        self.aboutMenu.addAction(self.aboutApp)
        self.menuBar.addAction(self.goToBeauty.menuAction())
        self.menuBar.addAction(self.aboutMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "表特板下載器-BeautyDownloader 1.0", None))
        self.choosePathLabel.setText(_translate("MainWindow", "預設路徑", None))
        self.choosePathButton.setText(_translate("MainWindow", "選擇路徑", None))
        self.label_3.setText(_translate("MainWindow", "目前表特板共有", None))
        self.allPageNumLabel.setText(_translate("MainWindow", "頁數", None))
        self.label.setText(_translate("MainWindow", "頁", None))
        self.label_4.setText(_translate("MainWindow", "，請輸入要下載的頁數範圍", None))
        self.label_2.setText(_translate("MainWindow", "到", None))
        self.sendPageButton.setText(_translate("MainWindow", "解析", None))
        self.stopSend.setText(_translate("MainWindow", "停止解析", None))
        self.tellTitleNumLabel.setText(_translate("MainWindow", "點擊解析", None))
        self.downloadButton.setText(_translate("MainWindow", "下載", None))
        self.randomBeauty.setText(_translate("MainWindow", "每日一表特", None))
        self.openFolder.setText(_translate("MainWindow", "開啟下載資料夾", None))
        self.QuitButton.setText(_translate("MainWindow", "QUIT", None))
        self.goToBeauty.setTitle(_translate("MainWindow", "前往表特版", None))
        self.aboutMenu.setTitle(_translate("MainWindow", "關於", None))
        self.helpMenu.setText(_translate("MainWindow", "使用說明", None))
        self.aboutApp.setText(_translate("MainWindow", "關於此軟體", None))

